"""Add unique constraint to users.email and cascade deletes for auth tokens.

Revision ID: 20240614_add_auth_constraints
Revises: None
Create Date: 2024-06-14 12:00:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20240614_add_auth_constraints"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add unique constraint to users.email (if not already present)
    op.create_unique_constraint("uq_users_email", "users", ["email"])

    # Ensure refresh_tokens.user_id cascade delete
    op.drop_constraint("refresh_tokens_user_id_fkey", "refresh_tokens", type_="foreignkey", if_exists=True)
    op.create_foreign_key(
        "fk_refresh_tokens_user_id",
        "refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # Ensure email_tokens.user_id cascade delete
    op.drop_constraint("email_tokens_user_id_fkey", "email_tokens", type_="foreignkey", if_exists=True)
    op.create_foreign_key(
        "fk_email_tokens_user_id",
        "email_tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop cascade foreign keys
    op.drop_constraint("fk_email_tokens_user_id", "email_tokens", type_="foreignkey")
    op.create_foreign_key(
        "email_tokens_user_id_fkey",
        "email_tokens",
        "users",
        ["user_id"],
        ["id"],
    )

    op.drop_constraint("fk_refresh_tokens_user_id", "refresh_tokens", type_="foreignkey")
    op.create_foreign_key(
        "refresh_tokens_user_id_fkey",
        "refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
    )

    # Drop unique constraint on users.email
    op.drop_constraint("uq_users_email", "users", type_="unique")
    # ### end Alembic commands ###
