import type { ResumeData } from "@/types/resume"

export const sampleResumeData: ResumeData = {
  id: "preview-sample",
  name: "Sample Resume",
  targetRole: "Software Engineer",
  targetIndustry: "Technology",
  sections: [
    { id: "contact", type: "contact", title: "Contact", order: 0, visible: true },
    { id: "summary", type: "summary", title: "Professional Summary", order: 1, visible: true },
    { id: "experience", type: "experience", title: "Experience", order: 2, visible: true },
    { id: "education", type: "education", title: "Education", order: 3, visible: true },
    { id: "skills", type: "skills", title: "Skills", order: 4, visible: true },
    { id: "languages", type: "languages", title: "Languages", order: 5, visible: true },
    { id: "certifications", type: "certifications", title: "Certifications", order: 6, visible: true },
    { id: "projects", type: "projects", title: "Projects", order: 7, visible: true },
    { id: "awards", type: "awards", title: "Awards", order: 8, visible: false },
    { id: "interests", type: "interests", title: "Interests", order: 9, visible: false },
    { id: "references", type: "references", title: "References", order: 10, visible: false },
    { id: "custom", type: "custom", title: "Custom", order: 11, visible: false },
  ],
  content: {
    contact: {
      fullName: "Aulia Prameswari",
      title: "Software Engineer",
      email: "aulia.prameswari@example.com",
      phone: "+62 812 3456 7890",
      location: "Jakarta, Indonesia",
      website: "auliaprameswari.dev",
      linkedin: "https://linkedin.com/in/auliaprameswari",
      github: "https://github.com/auliaprameswari",
      photoUrl: "",
    },
    summary:
      "Software Engineer with 6 years of experience building web applications and backend services in fast-paced technology environments. Strong in translating product requirements into scalable technical solutions, improving system reliability, and collaborating closely with cross-functional teams. Brings a practical, user-focused approach to development with experience across e-commerce and SaaS.",
    jobDescription: "",
    experience: [
      {
        id: "exp_1",
        company: "Gojek",
        role: "Senior Software Engineer",
        startDate: "Jan 2022",
        endDate: "Present",
        current: true,
        location: "Jakarta, Indonesia",
        bullets: [
          "Architected and delivered a real-time order tracking system serving 5M+ daily users, reducing latency by 35% through optimized WebSocket and Redis caching strategies",
          "Led a cross-functional team of 6 engineers to migrate legacy monolith to microservices, achieving 99.9% uptime during the cutover",
          "Designed and implemented CI/CD pipelines using GitHub Actions and ArgoCD, reducing deployment time from 45 minutes to 8 minutes",
          "Mentored 4 junior engineers through structured code reviews, pair programming, and weekly knowledge-sharing sessions",
        ],
      },
      {
        id: "exp_2",
        company: "Tokopedia",
        role: "Software Engineer",
        startDate: "Mar 2020",
        endDate: "Dec 2021",
        current: false,
        location: "Jakarta, Indonesia",
        bullets: [
          "Built and maintained the checkout and payment gateway integration handling 500K+ daily transactions with 99.95% success rate",
          "Developed a feature flag system using LaunchDarkly that enabled progressive rollouts and reduced production incidents by 60%",
          "Optimized PostgreSQL query performance by restructuring indexes and rewriting N+1 queries, cutting average page load time by 40%",
        ],
      },
      {
        id: "exp_3",
        company: "Traveloka",
        role: "Associate Software Engineer",
        startDate: "Jun 2018",
        endDate: "Feb 2020",
        current: false,
        location: "Jakarta, Indonesia",
        bullets: [
          "Contributed to the hotel booking platform frontend using React and TypeScript, improving search result rendering performance by 50%",
          "Implemented automated E2E test suite with Cypress achieving 85% coverage across critical user flows",
          "Collaborated with product and design teams to launch a price comparison feature that increased conversion rate by 12%",
        ],
      },
    ],
    education: [
      {
        id: "edu_1",
        institution: "University of Indonesia",
        degree: "B.S.",
        field: "Computer Science",
        startDate: "2014",
        endDate: "2018",
        current: false,
        gpa: "3.85",
      },
      {
        id: "edu_2",
        institution: "Bandung Institute of Technology",
        degree: "M.S.",
        field: "Data Science",
        startDate: "2021",
        endDate: "2023",
        current: false,
        gpa: "3.92",
      },
    ],
    skills: [
      {
        id: "skg_1",
        name: "Core",
        skills: [
          "JavaScript",
          "TypeScript",
          "React",
          "Node.js",
          "REST APIs",
          "PostgreSQL",
          "Git",
          "Agile Development",
        ],
      },
    ],
    languages: [
      { id: "lang_1", name: "Indonesian", proficiency: "native" },
      { id: "lang_2", name: "English", proficiency: "fluent" },
    ],
    certifications: [
      { id: "cert_1", name: "AWS Certified Cloud Practitioner", issuer: "", date: "2023", url: "" },
      { id: "cert_2", name: "Professional Scrum Master I (PSM I)", issuer: "", date: "2022", url: "" },
      { id: "cert_3", name: "Google IT Automation with Python Certificate", issuer: "", date: "2021", url: "" },
    ],
    projects: [
      {
        id: "proj_1",
        name: "Open Source CLI Tool",
        role: "Creator & Maintainer",
        url: "github.com/auliaprameswari/cli-tool",
        startDate: "",
        endDate: "",
        bullets: ["Built a developer CLI tool for automated project scaffolding with 3K+ GitHub stars"],
      },
    ],
    awards: [],
    interests: [],
    references: [],
    custom: [],
  },
  theme: {
    primaryColor: "#000000",
    secondaryColor: "#0A0A0A",
    textColor: "#374151",
    backgroundColor: "#ffffff",
    accentColor: "#000000",
    fontFamily: "Inter, sans-serif",
    headingFont: "Inter, sans-serif",
    fontSize: "medium",
    spacing: "normal",
    sectionStyle: "underline",
  },
  templateId: "obsidian-edge",
  createdAt: "2024-01-15T00:00:00Z",
  updatedAt: "2024-06-01T00:00:00Z",
}
